### ISSUE TITLE
Use GitHub Actions instead of Travis CI

### ISSUE THREAD

**Issue by elyday** [localhorstviersen/adrastea#11]
Maybe we should use GitHub Actions instead of Travis CI. Using GitHub Actions it seems that deployment is also possible. For PHPUnit see link below.

- https://github.com/features/actions
- https://github.com/marketplace/actions/github-action-for-phpunit

**Comment by elyday** [comment]
@tschroefel How do you feel about that?

**Comment by tschroefel** [comment]
I don't have experience with either one of those. So I'm open for everything.
